import { useMemo } from "react";
import { COUNTRIES } from "../../../data/countries";
import { inlineCellSx } from "../../../utils/muiFieldSx";
import {
  INVOICE_CURRENCY_OPTIONS,
  sectionIconBoxSx,
  sectionShellSx,
} from "../constants/invoiceConstants";
import { hasRowInput } from "../utils/number";

export const useCreateInvoiceSectionProps = ({
  customerType,
  handleCustomerTypeChange,
  invoiceNumberPreview,
  issueDate,
  dueDate,
  currency,
  setFieldFromEvent,
  formErrors,
  customerIdLabel,
  customerIdRule,
  customerName,
  customerCountry,
  companyIdentifier,
  customerVatRegistered,
  handleCustomerVatRegisteredChange,
  customerVatNumber,
  customerAddress,
  customerPostCode,
  customerCity,
  customerEmail,
  savedCustomerOptions,
  selectedSavedCustomer,
  onCustomerNameAutocompleteChange,
  onCustomerNameAutocompleteInputChange,
  products,
  currencySign,
  itemList,
  updateRow,
  patchRow,
  addRow,
  vatRateOptions,
  isBusinessVatRegistered,
  deleteRow,
  productsRequiredError,
  defaultBusinessVatRate,
  includeInvoiceNote,
  invoiceNote,
  handleInvoiceNoteToggle,
  subtotal,
  discountTotal,
  vatLabel,
  vatTotal,
  grandTotal,
}) =>
  useMemo(
    () => ({
      documentSectionProps: {
        sectionShellSx,
        sectionIconBoxSx,
        customerType,
        onCustomerTypeChange: handleCustomerTypeChange,
        invoiceNumberPreview,
        issueDate,
        onIssueDateChange: setFieldFromEvent("issueDate"),
        dueDate,
        onDueDateChange: setFieldFromEvent("dueDate"),
        currency,
        onCurrencyChange: setFieldFromEvent("currency", (e) =>
          (e.target.value || "EUR").toUpperCase(),
        ),
        currencyOptions: INVOICE_CURRENCY_OPTIONS,
        errors: formErrors,
      },
      customerSectionProps: {
        sectionShellSx,
        sectionIconBoxSx,
        countries: COUNTRIES,
        customerType,
        customerIdLabel,
        customerIdRule,
        customerName,
        onCustomerNameChange: setFieldFromEvent("customerName"),
        customerCountry,
        onCustomerCountryChange: setFieldFromEvent("customerCountry"),
        companyIdentifier,
        onCompanyIdentifierChange: setFieldFromEvent(
          "companyIdentifier",
          (e) => e.target.value ?? "",
        ),
        customerVatRegistered,
        onCustomerVatRegisteredChange: handleCustomerVatRegisteredChange,
        customerVatNumber,
        onCustomerVatNumberChange: setFieldFromEvent("customerVatNumber"),
        customerAddress,
        onCustomerAddressChange: setFieldFromEvent("customerAddress"),
        customerPostCode,
        onCustomerPostCodeChange: setFieldFromEvent("customerPostCode"),
        customerCity,
        onCustomerCityChange: setFieldFromEvent("customerCity"),
        customerEmail,
        onCustomerEmailChange: setFieldFromEvent("customerEmail"),
        savedCustomerOptions,
        selectedSavedCustomer,
        onCustomerNameAutocompleteChange,
        onCustomerNameAutocompleteInputChange,
        errors: formErrors,
      },
      productsSectionProps: {
        sectionShellSx,
        sectionIconBoxSx,
        inlineCellSx,
        products,
        currencySign,
        itemList,
        isMeaningfulRow: hasRowInput,
        updateRow,
        patchRow,
        addRow,
        vatRateOptions,
        showVatField: isBusinessVatRegistered,
        deleteRow,
        itemErrors: formErrors.itemList || [],
        showRequiredError: productsRequiredError || Boolean(formErrors.itemList),
        defaultBusinessVatRate,
      },
      invoiceNoteSectionProps: {
        includeInvoiceNote,
        invoiceNote,
        noteError: formErrors.invoiceNote?.message,
        onToggle: handleInvoiceNoteToggle,
        onChange: setFieldFromEvent("invoiceNote"),
      },
      totalsProps: {
        currencySign,
        subtotal,
        discountTotal,
        vatLabel,
        vatTotal,
        grandTotal,
        showVatAmount: isBusinessVatRegistered,
      },
    }),
    [
      addRow,
      companyIdentifier,
      currency,
      currencySign,
      customerAddress,
      customerCity,
      customerCountry,
      customerEmail,
      customerIdLabel,
      customerIdRule,
      customerName,
      customerPostCode,
      customerType,
      customerVatNumber,
      customerVatRegistered,
      defaultBusinessVatRate,
      deleteRow,
      discountTotal,
      dueDate,
      formErrors,
      grandTotal,
      handleCustomerTypeChange,
      handleCustomerVatRegisteredChange,
      handleInvoiceNoteToggle,
      includeInvoiceNote,
      invoiceNote,
      invoiceNumberPreview,
      isBusinessVatRegistered,
      issueDate,
      itemList,
      patchRow,
      products,
      productsRequiredError,
      savedCustomerOptions,
      selectedSavedCustomer,
      onCustomerNameAutocompleteChange,
      onCustomerNameAutocompleteInputChange,
      setFieldFromEvent,
      subtotal,
      updateRow,
      vatLabel,
      vatRateOptions,
      vatTotal,
    ],
  );
